# This file was generated by GoReleaser. DO NOT EDIT.
cask "extract-sbom" do
  version "0.5.11"

  on_macos do
    on_arm do
      sha256 "c2adedc789772265c2fa3153710bfa2401424b6ec933bd0dd92a2ed3c46a96e9"
      url "https://github.com/TomTonic/extract-sbom/releases/download/v#{version}/extract-sbom_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "91d1f444e2b851759fa1c3e477c6157a3742f43e1f1d941ee39561c77fba3320"
      url "https://github.com/TomTonic/extract-sbom/releases/download/v#{version}/extract-sbom_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e4ac7a5f3ad1b70aa14c5628ea9ee3ee72ce9949fc2eac7232cb404450b683bd"
      url "https://github.com/TomTonic/extract-sbom/releases/download/v#{version}/extract-sbom_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "603589563363a501039ef4fca4109d657e7938aaccf39e2996637698df5b8c65"
      url "https://github.com/TomTonic/extract-sbom/releases/download/v#{version}/extract-sbom_#{version}_linux_amd64.tar.gz"
    end
  end

  name "extract-sbom"
  desc "Recursively unpacks software deliveries into one SBOM and audit report"
  homepage "https://github.com/TomTonic/extract-sbom"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "sevenzip",
      "squashfs",
      "unshield",
    ]

  binary "extract-sbom"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/extract-sbom"],
                   must_succeed: false
  end

  # No zap stanza required

  caveats <<~EOS
    Some input formats (CAB, 7z, MSI, RAR, InstallShield, Squashfs) need external tools that are not bundled - see https://github.com/TomTonic/extract-sbom/blob/main/INSTALL.md
  EOS
end
