# This file was generated by GoReleaser. DO NOT EDIT.
cask "extract-sbom" do
  postflight_steps do
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "extract-sbom"],
        chdir: ".",
        must_succeed: false,
        writable_paths: ["extract-sbom"]
  end

  version "0.5.15"

  on_macos do
    on_arm do
      sha256 "e308d7c84eb44706d03a21ababdcf0f4ebadcf7846611227aaad08161043d502"
      url "https://github.com/TomTonic/extract-sbom/releases/download/v#{version}/extract-sbom_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "31ad5f38428eee965cd7ade6caab344830166df9885b5044f284da1e3a9c71a1"
      url "https://github.com/TomTonic/extract-sbom/releases/download/v#{version}/extract-sbom_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1399f65043589056b46f0d0530e11b8f41f7c34627243aa12a085a4ebefef08e"
      url "https://github.com/TomTonic/extract-sbom/releases/download/v#{version}/extract-sbom_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "78ef8a1a38cd2c8ffa686b454a7a4c59161e679dc46eb0bdb4d0990fca511b3d"
      url "https://github.com/TomTonic/extract-sbom/releases/download/v#{version}/extract-sbom_#{version}_linux_amd64.tar.gz"
    end
  end

  name "extract-sbom"
  desc "Recursively unpacks software deliveries into one SBOM and audit report"
  homepage "https://github.com/TomTonic/extract-sbom"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "sevenzip",
      "squashfs",
      "unshield",
    ]

  binary "extract-sbom"

  # No zap stanza required

  caveats <<~EOS
    Some input formats (CAB, 7z, MSI, RAR, InstallShield, Squashfs) need external tools that are not bundled - see https://github.com/TomTonic/extract-sbom/blob/main/INSTALL.md
  EOS
end
