# This file was generated by GoReleaser. DO NOT EDIT.
cask "extract-sbom" do
  postflight_steps do
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "extract-sbom"],
        chdir: ".",
        must_succeed: false,
        writable_paths: ["extract-sbom"]
  end

  version "0.5.13"

  on_macos do
    on_arm do
      sha256 "bf8790dc53535b9d2af0ed9d523e99ea53a8244d7620efe0a90e68ca14ab6e3d"
      url "https://github.com/TomTonic/extract-sbom/releases/download/v#{version}/extract-sbom_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f636ac5db1c99ce48877b4bd86f97891655dd48e3f7ecab8afaca9a822f856c2"
      url "https://github.com/TomTonic/extract-sbom/releases/download/v#{version}/extract-sbom_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "adb6bf00b698e5ce258cce8e40bef8734a3e922922f3d021d3af844197695ccd"
      url "https://github.com/TomTonic/extract-sbom/releases/download/v#{version}/extract-sbom_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "69136b296ec71e391878ce5cf067b8a02dbd0895aecffedb93b27472466984c0"
      url "https://github.com/TomTonic/extract-sbom/releases/download/v#{version}/extract-sbom_#{version}_linux_amd64.tar.gz"
    end
  end

  name "extract-sbom"
  desc "Recursively unpacks software deliveries into one SBOM and audit report"
  homepage "https://github.com/TomTonic/extract-sbom"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "sevenzip",
      "squashfs",
      "unshield",
    ]

  binary "extract-sbom"

  # No zap stanza required

  caveats <<~EOS
    Some input formats (CAB, 7z, MSI, RAR, InstallShield, Squashfs) need external tools that are not bundled - see https://github.com/TomTonic/extract-sbom/blob/main/INSTALL.md
  EOS
end
