# This file was generated by GoReleaser. DO NOT EDIT.
cask "prune_backups" do
  postflight_steps do
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "prune_backups"],
        chdir: ".",
        must_succeed: false,
        writable_paths: ["prune_backups"]
  end

  version "0.10.5"

  on_macos do
    on_arm do
      sha256 "3dec9061ae61987a9f4adbdcf9c623bccfd4b1a97639729c214e98df809c74cf"
      url "https://github.com/TomTonic/prune_backups/releases/download/v#{version}/prune_backups_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2aad8a3b9636bee03c9e91ff467f4105869fc7a9c4afc4d2cf88fde0eaf27d29"
      url "https://github.com/TomTonic/prune_backups/releases/download/v#{version}/prune_backups_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0925d2416a7988c5b9c6a666b93ae63ace40740a164c1341f54a96f25e44f087"
      url "https://github.com/TomTonic/prune_backups/releases/download/v#{version}/prune_backups_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cea542aa6a359d102f05d3dffdaa84df1cc2d8bfe32967a8a1edb319a431fc8f"
      url "https://github.com/TomTonic/prune_backups/releases/download/v#{version}/prune_backups_#{version}_linux_amd64.tar.gz"
    end
  end

  name "prune_backups"
  desc "Prune incremental backup directories on an hourly/daily/monthly schedule"
  homepage "https://github.com/TomTonic/prune_backups"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prune_backups"

  # No zap stanza required
end
